version: "3.9"

services:
  backend:
    image: ${CI_REGISTRY_IMAGE}/momo-backend:latest
    container_name: backend
    restart: always
    ports:
      - "8081:8081"    
    networks:
      - momo-store

  frontend:
    image: ${CI_REGISTRY_IMAGE}/momo-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    restart: always
    networks:
      - momo-store

networks:
  momo-store:
    driver: bridge