stages:
  - release
  - deploy

release-helm-chart:
  stage: release
  image: alpine/helm:3.14.4
  script:
    - helm package momo-store-chart
    - curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} ${NEXUS_HELM_REPO} --upload-file sausage-store-*.tgz
  only:
    changes:
      - momo-store-chart/**/*

deploy-helm-chart:
  stage: deploy
  image: alpine/helm:3.14.4
  before_script:
    - mkdir ~/.kube
    - echo ${KUBECONFIG} | base64 -d > ~/.kube/config
    - export KUBECONFIG=~/.kube/config
  script:
    - helm repo add nexus ${NEXUS_HELM_REPO} --username ${NEXUS_REPO_USER} --password ${NEXUS_REPO_PASS}
    - helm repo update
    - helm upgrade --install momo-store --atomic --timeout 15m nexus/momo-store