---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: momo-{{ .Chart.Name }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/part-of: momo-store
    env: "{{ .Values.global.environment }}"
spec:
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  replicas: {{ .Values.global.backend.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.global.backend.port }}"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - image: "{{ .Values.global.backend.image }}:{{ .Values.global.backend.tag }}"
          name: {{ .Chart.Name }}
          imagePullPolicy: Always
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.global.backend.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.global.backend.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret
